services:

  bot:
    build: .
    depends_on:
      - database
    volumes:
      - ./src:/app
    env_file: .env

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reminders

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
