# Generated by Django 3.1.7 on 2021-03-15 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('date_hour', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
